# Custom Language File for Launcher Customizer

[ejs.app]
title = "BearTycoon Launcher"

[ejs.landing]
mediaLinkURL = "https://candle-bougon-131.notion.site/1-15b20a105939808eab45c464129a7758"
mediaGitHubURL = "https://github.com/Rodin1a/BearTycoonLauncher/wiki"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/qbJUMJW6P4"

[ejs.settings]
sourceGithubLink = "https://github.com/Rodin1a/BearTycoonLauncher"
supportLink = "https://github.com/Rodin1a/BearTycoonLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bear Tycoon Season 2"
welcomeDescription = "Bear Tycoon Season 2"
welcomeDescCTA = "지금 시작합니다."
