# Custom Language File for Launcher Customizer

[ejs.app]
title = "BearTycoon Launcher"

[ejs.landing]
mediaLinkURL = "https://mysticred.space"
mediaGitHubURL = "https://github.com/Rodin1a/BearTycoonLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/Z8j6ahF4MJ"

[ejs.settings]
sourceGithubLink = "https://github.com/Rodin1a/BearTycoonLauncher"
supportLink = "https://github.com/Rodin1a/BearTycoonLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bear Tycoon Season 2"
welcomeDescription = "Bear Tycoon Season 2"
welcomeDescCTA = "지금 시작합니다."
