name: Build

on: push

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(node -p -e "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$VERSION"

      - name: Check if Release Exists
        id: check_release
        run: |
          if gh release view v${{ steps.get_version.outputs.version }}; then
            echo "Release already exists"
            exit 0
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        if: steps.check_release.outcome != 'success'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: BTY Launcher v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

  build_and_upload:
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist
        shell: bash

      - name: Upload Windows Asset
        if: matrix.os == 'windows-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./dist/BTY-Launcher-setup-${{ needs.create_release.outputs.version }}.exe
          asset_name: BTY-Launcher-setup-${{ needs.create_release.outputs.version }}.exe
          asset_content_type: application/octet-stream

      - name: Upload macOS Asset-x64
        if: matrix.os == 'macos-latest' && matrix.arch == 'x64'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./dist/BTY-Launcher-setup-${{ needs.create_release.outputs.version }}-x64.dmg
          asset_name: BTY-Launcher-setup-${{ needs.create_release.outputs.version }}-x64.dmg
          asset_content_type: application/octet-stream

      - name: Upload macOS Asset-arm64
        if: matrix.os == 'macos-latest' && matrix.arch == 'arm64'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./dist/BTY-Launcher-setup-${{ needs.create_release.outputs.version }}-arm64.dmg
          asset_name: BTY-Launcher-setup-${{ needs.create_release.outputs.version }}-arm64.dmg
          asset_content_type: application/octet-stream

      - name: Upload Linux Asset
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./dist/BTY-Launcher-setup-${{ needs.create_release.outputs.version }}.AppImage
          asset_name: BTY-Launcher-setup-${{ needs.create_release.outputs.version }}.AppImage
          asset_content_type: application/octet-stream